/**
 * @fileoverview ws-routes — registers the digital-human WebSocket route on the
 * WinClaw Gateway and wires inbound messages to the correct
 * {@link SessionManager} / {@link RealtimeSessionHandler} methods.
 *
 * Design reference: §8.5 of winclaw-avatar-digital-human-realtime-voice-plan.md
 *
 * Route registered:
 *   WS  /api/dh/connect/:sessionToken
 *
 * Protocol — inbound messages from the browser (JSON-encoded):
 * ```jsonc
 * // Audio chunk (PCM16 LE 16 kHz mono, base64-encoded)
 * { "type": "audio", "data": "<base64>" }
 *
 * // Video frame (JPEG/PNG, base64-encoded)
 * { "type": "video", "data": "<base64>" }
 *
 * // User text message
 * { "type": "text", "text": "帮我查明天的天气" }
 *
 * // Keep-alive ping
 * { "type": "ping" }
 *
 * // Client-initiated session stop
 * { "type": "stop" }
 * ```
 *
 * Protocol — outbound messages to the browser (JSON-encoded):
 * ```jsonc
 * { "type": "session.created", "sessionId": "...", "config": { ... } }
 * { "type": "dh_stream_info", "data": { "liveId": "...", ... } }
 * { "type": "ai_audio",  "data": { "audio": "<base64>", "format": "pcm16", "sample_rate": 24000 } }
 * { "type": "ai_text",   "data": { "content": "...", "is_delta": true|false } }
 * { "type": "user_transcript", "data": { "content": "..." } }
 * { "type": "ai_response_started" }
 * { "type": "ai_response_done" }
 * { "type": "pong" }
 * { "type": "error", "code": "...", "message": "...", "sessionId": "..." }
 * ```
 *
 * Authentication:
 *   The `:sessionToken` path parameter is validated against the WinClaw
 *   Gateway auth layer.  The `authenticateSessionToken` function in this file
 *   is the integration point; replace the stub with your actual auth logic.
 */

import type { IncomingMessage } from "node:http";
import WebSocket from "ws";
import type { RawData as WsRawData } from "ws";

import { SessionManager } from "./session-manager.js";
import type { SessionManagerConfig } from "./session-manager.js";
import type { DigitalHumanConfig } from "./config.js";

export { SessionManager };
export type { SessionManagerConfig };

// ---------------------------------------------------------------------------
// Gateway API surface (types provided by the WinClaw plugin-sdk at runtime)
// ---------------------------------------------------------------------------

/**
 * Minimal subset of the WinClaw Gateway API required to register routes.
 * Replace with the concrete type from `winclaw/plugin-sdk` when available.
 */
export interface GatewayAPI {
  /**
   * Register a WebSocket upgrade route on the gateway HTTP server.
   * Path patterns may use `:param` named segments.
   *
   * @param path    - Route path pattern (e.g. `"/api/dh/connect/:sessionToken"`).
   * @param handler - Handler invoked once per upgrade.
   */
  registerWsRoute(
    path: string,
    handler: (ctx: WsRouteContext) => Promise<void> | void,
  ): void;
}

/** Context passed to a WebSocket route handler. */
export interface WsRouteContext {
  /** The fully upgraded WebSocket connection. */
  socket: WebSocket;
  /** The triggering HTTP upgrade request. */
  req: IncomingMessage;
  /** Named path parameters extracted from the route pattern. */
  params: Record<string, string>;
}

// ---------------------------------------------------------------------------
// Authentication stub
// ---------------------------------------------------------------------------

/**
 * Result of session-token authentication.
 */
interface AuthResult {
  /** `true` when the token is valid. */
  valid: boolean;
  /** Client identifier (e.g. user ID) when valid; `undefined` otherwise. */
  clientId?: string;
}

/**
 * Validate a session token from the route path parameter.
 *
 * **Replace this stub** with your actual authentication logic (e.g. JWT
 * verification against the WinClaw API Key store or Gateway session table).
 *
 * The current implementation accepts any non-empty token to allow development
 * without a live auth backend.  In production, tokens should be single-use
 * short-lived JWTs generated by `POST /api/dh/session` on the HTTP layer.
 *
 * @param token - The raw `:sessionToken` value from the URL path.
 * @param req   - The HTTP upgrade request (may carry auth headers).
 * @returns     `{ valid: true, clientId: ... }` or `{ valid: false }`.
 */
async function authenticateSessionToken(
  token: string,
  _req: IncomingMessage,
): Promise<AuthResult> {
  if (!token || token.length < 8) {
    return { valid: false };
  }
  // TODO: replace with real JWT / API-Key validation.
  return { valid: true, clientId: `client-${token.slice(0, 8)}` };
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Generate a cryptographically random session ID.
 *
 * Uses `crypto.randomUUID()` when available (Node 19+); falls back to a
 * timestamp + random combination for older runtimes.
 */
function generateSessionId(): string {
  if (typeof crypto !== "undefined" && typeof crypto.randomUUID === "function") {
    return crypto.randomUUID();
  }
  return `dh-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 10)}`;
}

/**
 * Safely send a JSON message over a WebSocket, swallowing errors.
 *
 * @param ws  - Target WebSocket.
 * @param msg - Any JSON-serialisable value.
 */
function safeSend(ws: WebSocket, msg: unknown): void {
  try {
    if (ws.readyState === WebSocket.OPEN) {
      ws.send(JSON.stringify(msg));
    }
  } catch (err) {
    console.error("[ws-routes] safeSend error:", err);
  }
}

/**
 * Extract the remote IP address from an HTTP request, respecting common
 * reverse-proxy headers.
 *
 * @param req - Incoming HTTP request.
 */
function getClientIp(req: IncomingMessage): string {
  const forwarded = req.headers["x-forwarded-for"];
  if (typeof forwarded === "string") {
    return forwarded.split(",")[0]?.trim() ?? "unknown";
  }
  return req.socket.remoteAddress ?? "unknown";
}

// ---------------------------------------------------------------------------
// Inbound message types
// ---------------------------------------------------------------------------

/** Discriminated union of all message shapes the browser may send. */
export type InboundMessage =
  | { type: "audio"; data: string }
  | { type: "video"; data: string }
  | { type: "text"; text: string }
  | { type: "ping" }
  | { type: "stop" };

/**
 * Validate and narrow a raw parsed object to {@link InboundMessage}.
 *
 * Returns `null` for unrecognised or malformed messages.
 *
 * @param raw - The result of `JSON.parse` on the WebSocket payload.
 */
export function parseInboundMessage(raw: unknown): InboundMessage | null {
  if (!raw || typeof raw !== "object") return null;
  const msg = raw as Record<string, unknown>;

  switch (msg["type"]) {
    case "audio":
      if (typeof msg["data"] === "string") {
        return { type: "audio", data: msg["data"] };
      }
      return null;

    case "video":
      if (typeof msg["data"] === "string") {
        return { type: "video", data: msg["data"] };
      }
      return null;

    case "text":
      if (typeof msg["text"] === "string") {
        return { type: "text", text: msg["text"] };
      }
      return null;

    case "ping":
      return { type: "ping" };

    case "stop":
      return { type: "stop" };

    default:
      return null;
  }
}

// ---------------------------------------------------------------------------
// Route registration
// ---------------------------------------------------------------------------

/**
 * Register the digital-human WebSocket route on the WinClaw Gateway.
 *
 * Creates a shared {@link SessionManager} instance that persists for the
 * lifetime of the Gateway process.  Each inbound WebSocket upgrade creates a
 * new {@link RealtimeSessionHandler} inside the manager.
 *
 * The manager's timeout checker is started immediately and must be stopped
 * via the returned `dispose()` function when the Gateway shuts down.
 *
 * @param gateway - The Gateway API object provided by the WinClaw plugin SDK.
 * @param config  - Validated plugin configuration.
 * @param managerConfig - Full dependency set for {@link SessionManager}.
 * @returns A `dispose()` function that shuts down all sessions and stops
 *          the timeout checker — call this on Gateway exit.
 *
 * @example
 * ```typescript
 * const dispose = registerDigitalHumanRoutes(gateway, config, {
 *   config,
 *   workspaceDir: '/home/user/.winclaw/workspace',
 *   agentRunner,
 *   memoryPlugin,
 *   agentId: 'digital-human',
 * });
 *
 * process.on('SIGTERM', async () => {
 *   await dispose();
 *   process.exit(0);
 * });
 * ```
 */
/** Return value of {@link registerDigitalHumanRoutes}. */
export interface DigitalHumanRouteHandle {
  /** Shuts down all sessions and stops the timeout checker. */
  dispose: () => Promise<void>;
  /** The shared SessionManager instance (used by HTTP admin routes). */
  manager: SessionManager;
}

export function registerDigitalHumanRoutes(
  gateway: GatewayAPI,
  config: DigitalHumanConfig,
  managerConfig: SessionManagerConfig,
): DigitalHumanRouteHandle {
  const manager = new SessionManager(managerConfig);
  manager.startTimeoutChecker();

  // ── WS /api/dh/connect/:sessionToken ─────────────────────────────────────
  gateway.registerWsRoute(
    "/api/dh/connect/:sessionToken",
    async (ctx: WsRouteContext) => {
      const { socket, req, params } = ctx;
      const sessionToken = params["sessionToken"] ?? "";
      const clientIp = getClientIp(req);

      // ── Authentication ──────────────────────────────────────────────────
      const auth = await authenticateSessionToken(sessionToken, req);
      if (!auth.valid) {
        console.warn(
          `[ws-routes] Rejected unauthorized connection from ${clientIp} (token: ${sessionToken.slice(0, 8)}…)`,
        );
        safeSend(socket, {
          type: "error",
          code: "UNAUTHORIZED",
          message: "Invalid or expired session token",
        });
        socket.close(4001, "Unauthorized");
        return;
      }

      // ── Concurrent session cap check ────────────────────────────────────
      if (manager.activeCount >= config.session.maxConcurrent) {
        console.warn(
          `[ws-routes] Rejected connection: concurrent limit ${config.session.maxConcurrent} reached`,
        );
        safeSend(socket, {
          type: "error",
          code: "CONCURRENT_LIMIT",
          message: `Maximum concurrent sessions (${config.session.maxConcurrent}) reached`,
        });
        socket.close(1008, "Concurrent session limit reached");
        return;
      }

      // ── Create session ──────────────────────────────────────────────────
      const sessionId = generateSessionId();

      console.info(
        `[ws-routes] New connection: sessionId=${sessionId} clientId=${auth.clientId} ip=${clientIp}`,
      );

      // Send the session-created acknowledgement before initializing so the
      // client knows its assigned session ID while we connect to Qwen / DH.
      safeSend(socket, {
        type: "session.created",
        sessionId,
        config: {
          voice: config.qwen.voice,
          model: config.qwen.model,
          role: config.bytedance.role,
          timeoutMinutes: config.session.timeoutMinutes,
          maxConcurrent: config.session.maxConcurrent,
        },
      });

      // Initialize the session handler (connects to Qwen + ByteDance DH).
      let handler: ReturnType<typeof manager.getSession>;
      try {
        await manager.startSession(sessionId, socket);
        handler = manager.getSession(sessionId);
      } catch (err) {
        const message =
          err instanceof Error ? err.message : "Session initialization failed";
        console.error(
          `[ws-routes] Failed to start session ${sessionId}:`,
          err,
        );
        safeSend(socket, {
          type: "error",
          code: "SESSION_INIT_FAILED",
          message,
          sessionId,
        });
        socket.close(1011, "Session initialization failed");
        return;
      }

      // ── Message routing loop ────────────────────────────────────────────
      socket.on("message", (raw: WsRawData) => {
        // Register activity for the inactivity timeout.
        manager.touchActivity(sessionId);

        let parsed: unknown;
        try {
          parsed = JSON.parse(raw.toString());
        } catch {
          safeSend(socket, {
            type: "error",
            code: "INVALID_JSON",
            message: "Message payload is not valid JSON",
            sessionId,
          });
          return;
        }

        const msg = parseInboundMessage(parsed);
        if (!msg) {
          safeSend(socket, {
            type: "error",
            code: "UNKNOWN_MESSAGE_TYPE",
            message: `Unrecognised message type: ${(parsed as Record<string, unknown>)?.["type"] ?? "unknown"}`,
            sessionId,
          });
          return;
        }

        const currentHandler = manager.getSession(sessionId);
        if (!currentHandler) return; // Session already cleaned up.

        switch (msg.type) {
          case "audio":
            currentHandler.handleAudioMessage(msg.data);
            break;

          case "video":
            currentHandler.handleVideoMessage(msg.data);
            break;

          case "text":
            currentHandler.handleTextMessage(msg.text);
            break;

          case "ping":
            safeSend(socket, { type: "pong", sessionId });
            break;

          case "stop":
            // Client-initiated graceful disconnect.
            socket.close(1000, "Client requested session stop");
            break;
        }
      });

      // ── Graceful disconnect ─────────────────────────────────────────────
      socket.on("close", (code: number, reason: Buffer) => {
        const reasonStr = reason.toString();
        console.info(
          `[ws-routes] Session ${sessionId} closed: code=${code} reason="${reasonStr}"`,
        );
        // stopSession is idempotent — safe even if already removed by timeout.
        manager.stopSession(sessionId).catch((err) => {
          console.error(
            `[ws-routes] Error stopping session ${sessionId} on close:`,
            err,
          );
        });
      });

      // ── Error handling ──────────────────────────────────────────────────
      socket.on("error", (err: Error) => {
        console.error(
          `[ws-routes] WebSocket error on session ${sessionId}:`,
          err,
        );
        // Attempt to inform the client before the socket is torn down.
        safeSend(socket, {
          type: "error",
          code: "WEBSOCKET_ERROR",
          message: err.message,
          sessionId,
        });
        manager.stopSession(sessionId).catch((stopErr) => {
          console.error(
            `[ws-routes] Error stopping session ${sessionId} after WS error:`,
            stopErr,
          );
        });
      });

      // Suppress the linting warning — handler is used inside socket callbacks.
      void handler;
    },
  );

  // Return handle with dispose + manager reference.
  return {
    dispose: async (): Promise<void> => {
      console.info("[ws-routes] Gateway shutdown: stopping all sessions…");
      await manager.shutdownAll();
      manager.stopTimeoutChecker();
      console.info("[ws-routes] All digital-human sessions stopped");
    },
    manager,
  };
}
