/**
 * specInit.ts — Scaffold a per-feature spec directory under harness/specs/<id>/
 *
 * Public API consumed by Agent D's dispatcher ops.
 */

import fs from 'node:fs/promises'
import path from 'node:path'

export interface ActiveFeatureRecord {
  featureId: string
  displayName: string
}

export interface SpecInitResult {
  ok: boolean
  featureId: string
  displayName: string
  specsDir: string
  filesCreated: string[]
  activeFeatureFile: string
}

/** Zero-pad and prefix a feature ID with a sequential number */
async function nextFeatureNumber(specsDir: string): Promise<string> {
  let maxN = 0
  try {
    const names = await fs.readdir(specsDir)
    for (const rawName of names) {
      const name = String(rawName)
      try {
        const stat = await fs.stat(path.join(specsDir, name))
        if (!stat.isDirectory()) continue
      } catch {
        continue
      }
      const m = name.match(/^(\d+)-/)
      if (m) {
        const n = parseInt(m[1] ?? '0', 10)
        if (n > maxN) maxN = n
      }
    }
  } catch {
    // no existing dirs — that's fine
  }
  return String(maxN + 1).padStart(3, '0')
}

const SPEC_TEMPLATE = `# Feature Specification

## Overview
<!-- Describe the feature here -->

## Acceptance Criteria
<!-- List acceptance criteria as AC-001, AC-002, etc. -->

## Out of Scope
<!-- Explicitly note what is NOT included -->

## Open Questions
[NEEDS CLARIFICATION: fill in any open questions]
`

const PLAN_TEMPLATE = `# Implementation Plan

## Design Decisions
<!-- List key design decisions -->

## Architecture
<!-- Describe the approach -->
`

const TASKS_TEMPLATE = `# Tasks
<!-- Auto-generated by /harness phase advance (design → test-spec) -->
<!-- Run the advance to populate this file with decomposed tasks -->
`

/**
 * Create harness/specs/<NNN-featureName>/ skeleton and set as active feature.
 */
export async function initFeatureSpec(
  workspacePath: string,
  featureName: string,
): Promise<SpecInitResult> {
  const specsDir = path.join(workspacePath, 'harness', 'specs')
  await fs.mkdir(specsDir, { recursive: true })

  const num = await nextFeatureNumber(specsDir)
  const slug = featureName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '')
  const featureId = `${num}-${slug}`
  const featureDir = path.join(specsDir, featureId)

  await fs.mkdir(featureDir, { recursive: true })

  const filesCreated: string[] = []

  const filesToCreate: Array<[string, string]> = [
    ['spec.md', SPEC_TEMPLATE],
    ['plan.md', PLAN_TEMPLATE],
    ['tasks.md', TASKS_TEMPLATE],
  ]

  for (const [name, content] of filesToCreate) {
    const filePath = path.join(featureDir, name)
    await fs.writeFile(filePath, content, 'utf8')
    filesCreated.push(path.relative(workspacePath, filePath))
  }

  // Set active feature — store as JSON sidecar to preserve displayName alongside slug
  const auditDir = path.join(workspacePath, 'harness', 'audit')
  await fs.mkdir(auditDir, { recursive: true })
  const activeFeatureFile = path.join(auditDir, 'active-feature.txt')
  const record: ActiveFeatureRecord = { featureId, displayName: featureName }
  await fs.writeFile(activeFeatureFile, JSON.stringify(record), 'utf8')

  return {
    ok: true,
    featureId,
    displayName: featureName,
    specsDir: featureDir,
    filesCreated,
    activeFeatureFile: path.relative(workspacePath, activeFeatureFile),
  }
}
