/**
 * envScaffold.ts
 *
 * Generates a starter `.metacoder/environments.yaml` skeleton for fresh
 * projects created by /newproject.
 *
 * Defaults:
 *   - 3 envs: dev / staging / prod (or custom staging variant if envName given)
 *   - placeholder cloud config (AWS by default)
 *   - sensible safety defaults: dev=allow, staging=confirm, prod=deny
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type ScaffoldOptions = {
  /**
   * Custom env name to use as the "staging" tier.
   * E.g. "staging-eu" replaces the generic "staging" env.
   */
  stagingEnvName?: string

  /** Cloud provider for the scaffolded envs. Defaults to 'aws'. */
  cloudProvider?: 'aws' | 'azure' | 'gcp' | 'aliyun' | 'on-prem'

  /** AWS region / Azure region / GCP region */
  region?: string

  /** Whether to include a database section placeholder */
  includeDatabase?: boolean

  /** Deploy skill to embed in the prod env. Defaults to 'aws-cloud-deploy'. */
  deploySkill?: string
}

export type ScaffoldResult = {
  /** YAML text for .metacoder/environments.yaml */
  yaml: string
  /** Env names that were generated */
  envNames: string[]
  /**
   * Secret keys that should be registered in the OS credential store.
   * Caller should display these to the user.
   */
  secretsToRegister: string[]
  /**
   * Suggested CLI commands for registering secrets (platform-neutral comments
   * pointing to the relevant backend).
   */
  registrationHints: string[]
}

// ---------------------------------------------------------------------------
// Public: generateEnvScaffold
// ---------------------------------------------------------------------------

/**
 * Generate a complete environments.yaml skeleton for a brand-new project.
 */
export function generateEnvScaffold(options: ScaffoldOptions = {}): ScaffoldResult {
  const {
    stagingEnvName = 'staging',
    cloudProvider = 'aws',
    region = 'us-east-1',
    includeDatabase = false,
    deploySkill = defaultDeploySkill(cloudProvider),
  } = options

  const envNames = ['dev', stagingEnvName, 'prod']
  const secretsToRegister: string[] = []

  if (includeDatabase) {
    secretsToRegister.push('DB_PASS_DEV', `DB_PASS_${stagingEnvName.toUpperCase().replace(/-/g, '_')}`, 'DB_PASS_PROD')
  }

  const yaml = buildYaml({
    stagingEnvName,
    cloudProvider,
    region,
    includeDatabase,
    deploySkill,
    envNames,
  })

  const registrationHints = buildRegistrationHints(secretsToRegister)

  return { yaml, envNames, secretsToRegister, registrationHints }
}

// ---------------------------------------------------------------------------
// Internal builders
// ---------------------------------------------------------------------------

function defaultDeploySkill(provider: string): string {
  switch (provider) {
    case 'azure': return 'azure-cloud-deploy'
    case 'gcp':   return 'gcp-cloud-deploy'
    case 'aliyun': return 'aliyun-cloud-deploy'
    default:       return 'aws-cloud-deploy'
  }
}

type BuildYamlOptions = {
  stagingEnvName: string
  cloudProvider: string
  region: string
  includeDatabase: boolean
  deploySkill: string
  envNames: string[]
}

function buildYaml(opts: BuildYamlOptions): string {
  const { stagingEnvName, cloudProvider, region, includeDatabase, deploySkill } = opts

  const cloudDev    = cloudBlock(cloudProvider, region, 'dev')
  const cloudStg    = cloudBlock(cloudProvider, region, stagingEnvName)
  const cloudProd   = cloudBlock(cloudProvider, region, 'prod')

  const dbDev    = includeDatabase ? databaseBlock('dev')    : ''
  const dbStg    = includeDatabase ? databaseBlock(stagingEnvName) : ''
  const dbProd   = includeDatabase ? databaseBlock('prod')   : ''

  const stagingUpper = stagingEnvName.toUpperCase().replace(/-/g, '_')

  return [
    `# .metacoder/environments.yaml`,
    `# Generated by /newproject. Commit this file; keep secrets in OS credential store.`,
    `# Run: metacoder env import .env  — to import existing .env files.`,
    ``,
    `version: 2`,
    `default: dev`,
    ``,
    `environments:`,
    ``,
    `  # ── dev ───────────────────────────────────────────────────────────────`,
    `  - name: dev`,
    `    tags: [dev]`,
    `    description: Local development environment`,
    cloudDev,
    dbDev,
    `    safety:`,
    `      destructive_ops: allow     # dev: unrestricted`,
    ``,
    `  # ── ${stagingEnvName} ${'─'.repeat(Math.max(0, 56 - stagingEnvName.length))}`,
    `  - name: ${stagingEnvName}`,
    `    tags: [${stagingEnvName}]`,
    `    extends: dev`,
    `    description: Staging / pre-production environment`,
    cloudStg,
    dbStg,
    `    safety:`,
    `      destructive_ops: confirm   # staging: require confirmation`,
    ``,
    `  # ── prod ──────────────────────────────────────────────────────────────`,
    `  - name: prod`,
    `    tags: [production]`,
    `    extends: ${stagingEnvName}`,
    `    description: Production environment`,
    cloudProd,
    dbProd,
    `    deploy:`,
    `      skill: ${deploySkill}`,
    `      tested: false              # set true after first verified deploy`,
    `    safety:`,
    `      destructive_ops: deny      # prod: writes blocked without elevation`,
    `      writes_require_approval: true`,
    `      audit_log: .metacoder/audit/prod.log`,
    `      audit_log_retention: 1y`,
    ``,
    `# ── Secrets registration reminder ────────────────────────────────────────`,
    `# Register the following secrets in your OS credential store:`,
    ...(includeDatabase ? [
      `#   DB_PASS_DEV          — dev database password`,
      `#   DB_PASS_${stagingUpper.padEnd(16)} — ${stagingEnvName} database password`,
      `#   DB_PASS_PROD         — prod database password`,
    ] : []),
    `# Windows:  cmdkey /add:metacoder/<key> /user:metacoder /pass:<value>`,
    `# macOS:    security add-generic-password -s metacoder -a <key> -w <value>`,
    `# Linux:    secret-tool store --label='metacoder' key <key>`,
  ]
    .filter(line => line !== '')  // remove empty databaseBlock returns
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')   // collapse triple+ blank lines
}

function cloudBlock(provider: string, region: string, envSuffix: string): string {
  switch (provider) {
    case 'azure':
      return [
        `    cloud:`,
        `      provider: azure`,
        `      subscription: \${var:AZURE_SUBSCRIPTION_${envSuffix.toUpperCase().replace(/-/g, '_')}}`,
        `      region: ${region}`,
        `      resource_group: rg-${envSuffix}`,
      ].join('\n')

    case 'gcp':
      return [
        `    cloud:`,
        `      provider: gcp`,
        `      project: \${var:GCP_PROJECT_${envSuffix.toUpperCase().replace(/-/g, '_')}}`,
        `      region: ${region}`,
      ].join('\n')

    case 'aliyun':
      return [
        `    cloud:`,
        `      provider: aliyun`,
        `      access_key_id: \${var:ALIYUN_ACCESS_KEY_ID}`,
        `      access_key_secret: \${secret:ALIYUN_ACCESS_KEY_SECRET}`,
        `      region: ${region}`,
      ].join('\n')

    case 'on-prem':
      return [
        `    cloud:`,
        `      provider: on-prem`,
        `      host: server-${envSuffix}.internal`,
      ].join('\n')

    default: // aws
      return [
        `    cloud:`,
        `      provider: aws`,
        `      region: ${region}`,
        `      profile: ${envSuffix}`,
      ].join('\n')
  }
}

function databaseBlock(envSuffix: string): string {
  const upper = envSuffix.toUpperCase().replace(/-/g, '_')
  return [
    `    database:`,
    `      primary:`,
    `        type: postgres`,
    `        host: \${var:DB_HOST_${upper}}`,
    `        database: app_${envSuffix.replace(/-/g, '_')}`,
    `        user: \${var:DB_USER_${upper}}`,
    `        password: \${secret:DB_PASS_${upper}}`,
    `        ssl: require`,
  ].join('\n')
}

function buildRegistrationHints(secrets: string[]): string[] {
  if (secrets.length === 0) return []

  return [
    'Register the following secrets in your OS credential store:',
    ...secrets.map(s => `  ${s}`),
    '',
    'Windows (cmdkey):',
    ...secrets.map(s => `  cmdkey /add:metacoder/${s} /user:metacoder /pass:<value>`),
    '',
    'macOS (Keychain):',
    ...secrets.map(s => `  security add-generic-password -s metacoder -a ${s} -w <value>`),
    '',
    'Linux (libsecret):',
    ...secrets.map(s => `  secret-tool store --label='metacoder' key ${s}`),
  ]
}
