/**
 * github-actions/index.ts — GitHub Actions CI template for harness.
 *
 * Returns the content of the harness.yml workflow file as a string constant.
 * This is embedded in the init flow and written by /harness ci-init --target github.
 */

/**
 * Generate the GitHub Actions workflow YAML content.
 *
 * @param opts.nodeVersion - Node/Bun version hint (default: "latest")
 * @returns Content of .github/workflows/harness.yml
 */
export function githubActionsWorkflow(opts?: { bunVersion?: string }): string {
  const bunVersion = opts?.bunVersion ?? 'latest'
  return `# .github/workflows/harness.yml
# Harness Engineering CI — auto-generated by /harness ci-init --target github
# Edit gates-matrix to match the gate IDs in harness/workflow/gates.yaml

name: Harness Engineering

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

env:
  BUN_VERSION: "${bunVersion}"

jobs:
  # ---------------------------------------------------------------------------
  # Job 1: harness-validate
  # ---------------------------------------------------------------------------
  harness-validate:
    name: Validate harness layout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: \${{ env.BUN_VERSION }}

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
            node_modules
          key: \${{ runner.os }}-bun-\${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            \${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run harness validate
        run: |
          bun run --eval "
            import { loadHarness, validateLayout } from './src/services/harness/loader.js'
            const layout = await loadHarness(process.cwd())
            const result = await validateLayout(layout)
            if (!result.ok) {
              console.error(JSON.stringify(result.errors, null, 2))
              process.exit(1)
            }
            console.log('harness layout valid —', result.warnings.length, 'warnings')
          "

  # ---------------------------------------------------------------------------
  # Job 2: harness-lint
  # ---------------------------------------------------------------------------
  harness-lint:
    name: Harness rule lint
    runs-on: ubuntu-latest
    needs: [harness-validate]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: \${{ env.BUN_VERSION }}

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
            node_modules
          key: \${{ runner.os }}-bun-\${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            \${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run harness lint
        run: |
          bun run --eval "
            import { harnessLint } from './src/services/harness/lint.js'
            const result = await harnessLint(process.cwd())
            const violations = result.violations.filter(v => v.severity === 'error')
            if (violations.length > 0) {
              console.error(JSON.stringify(violations, null, 2))
              process.exit(1)
            }
            console.log('lint passed — score:', result.score + '/100')
          "

  # ---------------------------------------------------------------------------
  # Job 3: harness-gate (matrix over gate ids)
  # ---------------------------------------------------------------------------
  harness-gate:
    name: Gate — \${{ matrix.gate_id }}
    runs-on: ubuntu-latest
    needs: [harness-validate]
    strategy:
      fail-fast: false
      matrix:
        # Update this list to match the gate IDs in harness/workflow/gates.yaml
        gate_id:
          - gate-planning
          - gate-implementation
          - gate-review
          - gate-testing
    steps:
      - uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: \${{ env.BUN_VERSION }}

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
            node_modules
          key: \${{ runner.os }}-bun-\${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            \${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run gate \${{ matrix.gate_id }}
        env:
          GATE_ID: \${{ matrix.gate_id }}
        run: |
          bun run --eval "
            import { runGate } from './src/services/harness/gates/runner.js'
            const gateId = process.env.GATE_ID
            const result = await runGate(gateId, process.cwd())
            console.log(JSON.stringify(result, null, 2))
            if (!result.passed) process.exit(1)
          "

  # ---------------------------------------------------------------------------
  # Job 4: harness-drill (PR builds only)
  # ---------------------------------------------------------------------------
  harness-drill:
    name: Harness drill (PR)
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: [harness-validate]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: \${{ env.BUN_VERSION }}

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
            node_modules
          key: \${{ runner.os }}-bun-\${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            \${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run harness drill
        run: |
          echo "harness drill — placeholder until /harness drill is implemented"
          echo "PR: \${{ github.event.pull_request.number }}"

  # ---------------------------------------------------------------------------
  # Job 5: harness-ai-rate
  # ---------------------------------------------------------------------------
  harness-ai-rate:
    name: AI rating summary
    runs-on: ubuntu-latest
    needs: [harness-lint, harness-gate]
    if: always()
    steps:
      - uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: \${{ env.BUN_VERSION }}

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
            node_modules
          key: \${{ runner.os }}-bun-\${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            \${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Generate AI rating summary (JSON)
        run: |
          bun run --eval "
            import { harnessLint } from './src/services/harness/lint.js'
            const result = await harnessLint(process.cwd())
            const summary = {
              score: result.score,
              passed: result.passed,
              filesScanned: result.filesScanned,
              rulesEvaluated: result.rulesEvaluated,
              violationCount: result.violations.length,
              errorCount: result.violations.filter(v => v.severity === 'error').length,
              warningCount: result.violations.filter(v => v.severity === 'warning').length,
              generatedAt: new Date().toISOString(),
            }
            await import('node:fs').then(fs =>
              fs.promises.writeFile('harness-ai-rate-summary.json', JSON.stringify(summary, null, 2))
            )
            console.log(JSON.stringify(summary, null, 2))
          "

      - name: Upload AI rate summary artifact
        uses: actions/upload-artifact@v4
        with:
          name: harness-ai-rate-summary
          path: harness-ai-rate-summary.json
          retention-days: 30
`
}
