/**
 * gitlab/index.ts — GitLab CI template for harness.
 *
 * Returns the content of the .gitlab-ci.yml file as a string constant.
 * This is embedded in the init flow and written by /harness ci-init --target gitlab.
 */

/**
 * Generate the GitLab CI YAML content.
 *
 * @param opts.bunVersion - Bun version to use (default: "latest")
 * @param opts.gateIds - Gate IDs to include in the matrix (default: standard set)
 * @returns Content of .gitlab-ci.yml
 */
export function gitlabCiConfig(opts?: { bunVersion?: string; gateIds?: string[] }): string {
  const bunVersion = opts?.bunVersion ?? 'latest'
  const gateIds = opts?.gateIds ?? [
    'gate-planning',
    'gate-implementation',
    'gate-review',
    'gate-testing',
  ]

  const gateJobs = gateIds
    .map(
      (gateId) => `
gate:${gateId}:
  stage: gate
  extends: .bun_setup
  variables:
    GATE_ID: "${gateId}"
  script:
    - >
      bun run --eval "
        import { runGate } from './src/services/harness/gates/runner.js'
        const gateId = process.env.GATE_ID
        const result = await runGate(gateId, process.cwd())
        console.log(JSON.stringify(result, null, 2))
        if (!result.passed) process.exit(1)
      "
  allow_failure: false`,
    )
    .join('\n')

  return `# .gitlab-ci.yml
# Harness Engineering CI — auto-generated by /harness ci-init --target gitlab
# Edit gate:* jobs to match gate IDs in harness/workflow/gates.yaml

image: oven/bun:${bunVersion}

stages:
  - validate
  - lint
  - gate
  - drill
  - ai-rate

variables:
  BUN_VERSION: "${bunVersion}"
  # Cache directory for Bun packages
  BUN_CACHE_DIR: "\${CI_PROJECT_DIR}/.bun-cache"

# ---------------------------------------------------------------------------
# Shared setup template
# ---------------------------------------------------------------------------
.bun_setup:
  before_script:
    - bun install --frozen-lockfile
  cache:
    key:
      files:
        - bun.lockb
    paths:
      - node_modules/
      - .bun-cache/
    policy: pull-push

# ---------------------------------------------------------------------------
# Stage: validate
# ---------------------------------------------------------------------------
harness-validate:
  stage: validate
  extends: .bun_setup
  script:
    - >
      bun run --eval "
        import { loadHarness, validateLayout } from './src/services/harness/loader.js'
        const layout = await loadHarness(process.cwd())
        const result = await validateLayout(layout)
        if (!result.ok) {
          console.error(JSON.stringify(result.errors, null, 2))
          process.exit(1)
        }
        console.log('harness layout valid —', result.warnings.length, 'warnings')
      "

# ---------------------------------------------------------------------------
# Stage: lint
# ---------------------------------------------------------------------------
harness-lint:
  stage: lint
  extends: .bun_setup
  needs: [harness-validate]
  script:
    - >
      bun run --eval "
        import { harnessLint } from './src/services/harness/lint.js'
        const result = await harnessLint(process.cwd())
        const violations = result.violations.filter(v => v.severity === 'error')
        if (violations.length > 0) {
          console.error(JSON.stringify(violations, null, 2))
          process.exit(1)
        }
        console.log('lint passed — score:', result.score + '/100')
      "

# ---------------------------------------------------------------------------
# Stage: gate (parallel matrix)
# ---------------------------------------------------------------------------
${gateJobs}

# ---------------------------------------------------------------------------
# Stage: drill (MR builds only)
# ---------------------------------------------------------------------------
harness-drill:
  stage: drill
  extends: .bun_setup
  needs: [harness-validate]
  only:
    - merge_requests
  script:
    - echo "harness drill — placeholder until /harness drill is implemented"
    - echo "MR: \${CI_MERGE_REQUEST_IID}"

# ---------------------------------------------------------------------------
# Stage: ai-rate
# ---------------------------------------------------------------------------
harness-ai-rate:
  stage: ai-rate
  extends: .bun_setup
  needs:
    - harness-lint
    - job: gate:${gateIds[0] ?? 'gate-planning'}
      optional: true
  when: always
  script:
    - >
      bun run --eval "
        import { harnessLint } from './src/services/harness/lint.js'
        const result = await harnessLint(process.cwd())
        const summary = {
          score: result.score,
          passed: result.passed,
          filesScanned: result.filesScanned,
          rulesEvaluated: result.rulesEvaluated,
          violationCount: result.violations.length,
          errorCount: result.violations.filter(v => v.severity === 'error').length,
          warningCount: result.violations.filter(v => v.severity === 'warning').length,
          generatedAt: new Date().toISOString(),
        }
        import('node:fs').then(fs =>
          fs.promises.writeFile('harness-ai-rate-summary.json', JSON.stringify(summary, null, 2))
        )
        console.log(JSON.stringify(summary, null, 2))
      "
  artifacts:
    name: harness-ai-rate-\${CI_COMMIT_SHORT_SHA}
    paths:
      - harness-ai-rate-summary.json
    expire_in: 30 days
    reports:
      # Expose score as a GitLab metrics artifact for visibility in MRs
      metrics: harness-ai-rate-summary.json
`
}
